### ISSUE TITLE
Error in ifcToCoBieLiteUkExchanger

### ISSUE THREAD

**Issue by nourrt** [xBimTeam/XbimExchange#11]
I'm getting the following error when I try to convert an ifc file to a json file:

exception:System.NullReferenceException: Object reference not set to an instance of an object. at XbimExchanger.IfcToCOBieLiteUK.CoBieLiteUkHelper.GetUnits() in c:\BuildAgent\work\f46659e6f579ee7\Xbim.Exchanger\IfcToCOBieLiteUK\COBieLiteUKHelper.cs:line 975 at XbimExchanger.IfcToCOBieLiteUK.CoBieLiteUkHelper..ctor(XbimModel model, ProgressReporter reportProgress, OutPutFilters filter, String configurationFile, EntityIdentifierMode extId, SystemExtractionMode sysMode) in c:\BuildAgent\work\f46659e6f579ee7\Xbim.Exchanger\IfcToCOBieLiteUK\COBieLiteUKHelper.cs:line 257 at XbimExchanger.IfcToCOBieLiteUK.IfcToCOBieLiteUkExchanger..ctor(XbimModel source, List`1 target, ReportProgressDelegate reportProgress, OutPutFilters filter, String configFile, EntityIdentifierMode extId, SystemExtractionMode sysMode, Boolean classify) in c:\BuildAgent\work\f46659e6f579ee7\Xbim.Exchanger\IfcToCOBieLiteUK\IfcToCOBieLiteUkExchanger.cs:line 33 at WebApplication2.TestConversion.Page_Load(Object sender, EventArgs e)

at this line of code:  `var ifcToCoBieLiteUkExchanger = new IfcToCOBieLiteUkExchanger(m, facilities);`

Any help as to why I'm getting this error will be greatly appreciated.

**Comment by SteveLockley** [comment]
There is not enough information to repeat this, please reopen with sample files and or code
