### ISSUE TITLE
COBieLiteUK: Conversion from IFC: SerialNumber not mapped due mistake in embedded config

### ISSUE THREAD

**Issue by MichaelBuehler** [xBimTeam/XbimExchange#20]
Hello,

In Xbim.Exchanger > IfcToCOBieLiteUK, file COBieAttributes.config

   add key="AssetSerialNumber" value="Pset_ManufacturerOccurence.SerialNumber;Pset_Component.SerialNumber;Other.SerialNumber"
	
It should be Pset_ManufacturerOccurrence, not Pset_ManufacturerOccurence

**Comment by CBenghi** [comment]
Thanks @MichaelBuehler,
fixed in Commit hash:	9701bd430430ff41d908e41e1651e3d33d824d44
If you wish to fork the project and submit Pull requests you'd be welcome.
Best,
Claudio
