### ISSUE TITLE
Error converting IFC file to WeXBim

### ISSUE THREAD

**Issue by dazmahal** [xBimTeam/XbimExchange#23]
Issue occurs using Latest Development Branch of XBim.Exchange to convert ifc file (144 MB)

An unhandled exception of type 'System.AccessViolationException' occurred in Xbim.Geometry.Engine64.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by CBenghi** [comment]
@dazmahal,
I'm afraid that the current state of the information you provide is not sufficient to understand the problem.
This might be connected to a specific model you have, but without reproducible steps we cannot hep.

please have a look at:
https://wiredcraft.com/blog/how-we-write-our-github-issues/

Best,
Claudio
