### ISSUE TITLE
IFC to JSON: "sub" objects are missing

### ISSUE THREAD

**Issue by franky235** [xBimTeam/XbimExchange#25]
Hello,
I am converting IFC files to .wexbim and .json, 
working fine but I noticed some objects are missing in the .json file
like a IfcSlab (subpart of the IfcRoof), and IfcRailing(s) and IfcStairFlight(s) (subpart of IfcStair)
looks like "subparts" are missing in the .json
Not familiar with COBIE standard, my question is: is it normal of is it a bug ?

Thanks for your help,
Francois

**Comment by martin1cerny** [comment]
It is a requirement in COBieLiteUK structure for every component to have a type defined which is not the case for these aggregated elements. Data is created in this hierarchy so you will want to investigate [this](https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchanger/IfcToCOBieLiteUK/MappingXbimIfcProxyTypeObjectToAssetType.cs#L130) part of the code. COBieLiteUK is not actively maintained at the moment so you will have to make any such a change yourself.

**Comment by franky235** [comment]
Thanks for your guidance, I changed the code accordingly and I am ready to share it: what is the process ? (sorry I am newbie at github) are you expecting a pull request ? on dev branch ? how ?

**Comment by martin1cerny** [comment]
Yes, pull request to `develop` branch would be the best.

**Comment by theextremeandy** [comment]
hi @franky235, @martin1cerny ,
I have a similar problem
after conversion ifcPlate are missing in the .json
IFC file contains 229 ifcPlate obj like this:
#428522= IFCPLATE('1tghYAjEfBQuF89jQoGJnc',#12,'Pannel-Div-072',$,$,#427630,#428519,'77AAB88A-B4EA-4B6B-83C8-26D6B2413C66');
and 41 ifcPlateType:
#429511= IFCPLATETYPE('0lZzIx0zg90VSq6be1g1TA',#12,'Pannel 1130 x 1210 x 20',$,$,$,$,'2F8FD4BB-03DA-8901-F734-1A5A01A8174A',$,.NOTDEFINED.);
but no ifcPlate element in json file.
can you help me?
andrea

ps
Also, I try to change into COBieAttributes.config
from
<add key="IfcPlate" value="No"/>
to
<add key="IfcPlate" value="Yes"/>

**Comment by martin1cerny** [comment]
As you will guessed from the name of the project, this JSON is one of many possible forms of COBie. Not all IFC product types are supposed to go into COBie. I think `IfcPlate` is one of the excluded ones.

**Comment by theextremeandy** [comment]
Thank you @martin1cerny! 
I'm looking for the Cobie data scheme
but I believe you are certainly right
andrea

**Comment by I-Sokolov** [comment]
All building elements and types are excluded from COBie by default. 
You may customize COBieContext.Exclude passed to COBieBuilder constructor to change set of excluded types

**Comment by theextremeandy** [comment]
hi @I-Sokolov,
Thank you for your suggestion
I'm going to try the solution
/BR
andrea

**Comment by Princepra** [comment]
@franky235  , hi franky am facing problem in converting ifc to wexbim. Can you share the conversion code plz.

**Comment by franky235** [comment]
@Princepra, I use the example code found in documentation, nothing specific on my side: http://docs.xbim.net/examples/creating-wexbim-file.html

**Comment by martin1cerny** [comment]
Closing the issue as it is no longer related to the original question.
