### ISSUE TITLE
COBie example

### ISSUE THREAD

**Issue by MarcoGiorgi** [xBimTeam/XbimExchange#29]
I remember there was an example, on the docs.xbim.net website of C# code reading an IFC file to extract/view an excel file for COBie.
Now I can't find it anymore under the Example menu, where is it?

**Comment by andyward** [comment]
There's an example in the CobieExpress repo: https://github.com/xBimTeam/XbimCobieExpress#2-converting-ifcs-to-cobie-spreadheets
