### ISSUE TITLE
How to debug through xBimTeam sources?

### ISSUE THREAD

**Issue by I-Sokolov** [xBimTeam/XbimExchange#32]
I fetched XbimExchange, it downloaded xbim packages while build and can run now.  
Now I want to debug deep into XbimEssential.
How to switch XbimExchange to use local build of XbimEssential rather than take from nuget?

Sorry I did not find good answer in nuget related sources and I believe xBimTeam knows the best practice:)

**Comment by LloydPickering** [comment]
Run Xplorer (without debug), open Essentials project in another visual
studio instance and choose Debug > Attach to Process. In the dialog choose
Xplorer.

Now any breakpoints in Essentials will be hit.

(Make sure you are attaching the correct version of essentials to match the
nuget version you are using or else you will get warnings about a mismatch)

**Comment by I-Sokolov** [comment]
>>> Make sure you are attaching the correct version of essentials to match the nuget version

That's exactly my problem. 
Especially if I want to try some changes in local version of essential.

**Comment by CBenghi** [comment]
@I-Sokolov,
if you haven't solved yet we can discuss in our call on Monday.
Claudio

**Comment by andyward** [comment]
Assume we can close this now?
