### ISSUE TITLE
IFC4 support

### ISSUE THREAD

**Issue by I-Sokolov** [xBimTeam/XbimExchange#33]
IFC4 files are read now by IfcStore.Open but COBieBuilder fails.
First stop is in COBieDataFacility.Fill.
var ifcProject = Model.FederatedInstances.OfType<Ifc2x3.Kernel.IfcProject>().FirstOrDefault();

As I understand lines like this are to be reworked for IFC4

**Comment by CBenghi** [comment]
That's right @I-Sokolov,
should this become a priority for you let us know.
We can prioritise on demand, if agreed.
Best,
Claudio

**Comment by andyward** [comment]
I think it's going to be a "big ask" to support Ifc4 in the original `Xbim.Cobie` project. It wasn't built for multiple schemas. 

If you need to support Ifc4 => COBie I'd recommend taking a look at https://github.com/xBimTeam/XbimCobieExpress which is a lot more flexible. COBieExpress is demonstrated in the Xbim.COBieLiteUK.Client project in this repo.
