### ISSUE TITLE
wexbim + Custom CDE into IFC

### ISSUE THREAD

**Issue by redgeway-edocs** [xBimTeam/XbimExchange#4]
We are looking at generating an IFC with updated asset data from our own CDE.
We have used the xBim tools to seperate the IFC file into the geometry data (wexbim) and the asset data ( COBie ).

We then use our own CDE to update the asset data.

Is it then possible to use the wexbim file and our now updated data to regenerate a new IFC or would we be better off updating the data in the original IFC?

**Comment by CBenghi** [comment]
Hi,
Just my thoughs...
In principle creating a new IFC is feasible, but I suppose that it's going to be much easier to retain the original IFC file (xbim format is also ok) and push back the differences that you should have kept track of.

The Wexbim format flattens the complex structure of geometries for viewing purposes, but most BIM tools would do a better job at understanding the data using the rich geometric primitives of the IFC.

Authorship issues are also relevant... You want to be sure that data is not altered in ways that users cannot control before being sent across the CDE (small details might matter a lot in case of litigation).

**Comment by CBenghi** [comment]
I'm closing to tidy-up as no contribution has been posted in a while, please reopen or open a new one if needed.
Claudio
