### ISSUE TITLE
IFCQUANTITYLENGTH x IFCSIUNIT

### ISSUE THREAD

**Issue by BrunoMBuzzi** [xBimTeam/XbimExchange#40]
Hello everyone,

I have an IIfcProduct object, let's say this given product have the following quantities:
#4350= IFCQUANTITYLENGTH('Depth','',$,14.);
#4351= IFCQUANTITYLENGTH('Height','',$,59.9999999999998);
#4352= IFCQUANTITYLENGTH('Width','',$,51.0005334674172);

And I have the following units on the IFC file:
#42= IFCSIUNIT(*,.LENGTHUNIT.,.CENTI.,.METRE.);
#43= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#64= IFCSIUNIT(*,.LENGTHUNIT.,.DECI.,.METRE.);

How do I know which IFCSIUNIT belongs to each quantity using the IIfcProduct object?

Thanks,
Bruno.

![image](https://user-images.githubusercontent.com/39279756/46214495-b1d22600-c311-11e8-87a9-cf449397c614.png)

**Comment by andyward** [comment]
There's an optional Unit attribute on the IfcQuantityLength  http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcquantityresource/lexical/ifcquantitylength.htm

Where it's not set, you can infer the default length unit from the the IfcProject/IfcContext
