### ISSUE TITLE
How to reduce a time of conversion from ifc to xbim

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimExchange#5]
it takes a more time to convert on this line
      context.CreateContext(geomStorageType: XbimGeometryType.PolyhedronBinary);

.ANY SOLUTION FOR THIS TO OPTIMIZE THIS CODE.

**Comment by BIMDevelopement** [comment]
I am using 1) xbim.common dll with version 3.0.5620.24387 2) xbim.modelGemoetryScene dll with version 3.0.5624.26271.

**Comment by CBenghi** [comment]
Hello, that's the line where all the geometry meshing is happening.
Depending on the size of the model it might take several minutes to achieve the conversion.
The results can then be retained and cached in xbim files.
We have tried to convert very large files in acceptable times, is it possible for you to share (privately, if needed) the model you are having problems with?
As far as I can remember the current versions of geometry should be in the 3.1 family.
You can try to download the latest XbimXplorer (from source) to see if makes any difference.

**Comment by CBenghi** [comment]
By the way, if you are not interested in geometry, you can probably skip that line completely.
Geometry meshing is only used to calculate bounding boxes  for cobie.
I'm not sure if then some null exception might need to be dealt with, but it could be worth a try.
Claudio

**Comment by BIMDevelopement** [comment]
hi CBenghi ,

Yes , the conversion is done fast by removing that line. But , .wexbim file is created only 1 kb for every file. In context ,gemoetryCount is zero after removing that line.
So , it is not useful for me . I need wexbim file also.

**Comment by CBenghi** [comment]
Yes, sure, that's needed for meshing.
Still the time it takes for you is surprising.
Would you be able to share the model to run some test? 
I'd be happy to sign an NDA if needed.
Best,
Claudio
