### ISSUE TITLE
Taking a too much time to convert from ifc to wexbim 

### ISSUE THREAD

**Issue by Marks10** [xBimTeam/XbimExchange#6]
Hi ,
I am trying to convert 600MB ifc file ,It is converted but it takes a near about 1 hour for that.
Please help me to reduce time for this.

My hardware configuration is as follows:
1) NVIDIA graphics card- 2gb
2)
![configure](https://cloud.githubusercontent.com/assets/16130194/11558714/41c32cdc-99da-11e5-9d15-4d5b80e7177f.png)

**Comment by CBenghi** [comment]
This issue was moved to xBimTeam/XbimWebUI#120
