### ISSUE TITLE
Converting to wexbim - Removing elements from a .wexbim File to improve Performance

### ISSUE THREAD

**Issue by dazmahal** [xBimTeam/XbimExchange#7]
Hi folks
Query related to Converting to wexbim -
Our developer has worked on .json file removing any unwanted elements, and after the web optimization got  the payload down from 70mb to < 5mb.
Can we undergo a similar process with the .wexbim file - What type of elements can be removed without effecting its integrity?

Thanks
Darren

**Comment by CBenghi** [comment]
This issue was moved to xBimTeam/XbimWebUI#119
